export const FETCH_CAROUSEL  = "FETCH_CAROUSEL";
export const FETCH_ASUSEDBY = "FETCH_ASUSEDBY";
export const FETCH_NEEDWORKDONE = "FETCH_NEEDWORKDONE";
export const FETCH_ABOUTIT = "FETCH_ABOUTIT";
export const FETCH_FAVORITE = "FETCH_FAVORITE";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_APICARD = "FETCH_APICARD";
export const FETCH_JOB = "FETCH_JOB";